<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="YoutubeExplode">
      <HintPath>..\..\YoutubeDownloaderRU\YoutubeExplode.dll</HintPath>
    </Reference>
    <Reference Include="YoutubeExplode.Converter">
      <HintPath>..\..\YoutubeDownloaderRU\YoutubeExplode.Converter.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
